"""AI Analyst ORM models — daily reports and chat sessions."""

from datetime import datetime

from sqlalchemy import String, Float, DateTime, Text, Index
from sqlalchemy.types import JSON
from sqlalchemy.orm import Mapped, mapped_column

from .base import Base


class AIReport(Base):
    """Daily AI analysis report generated by Claude."""

    __tablename__ = "ai_reports"

    id: Mapped[int] = mapped_column(primary_key=True)
    report_date: Mapped[str] = mapped_column(String(10), index=True)
    report_type: Mapped[str] = mapped_column(String(20))  # "daily" / "weekly"
    market_regime: Mapped[str | None] = mapped_column(String(20), nullable=True)
    market_regime_confidence: Mapped[float | None] = mapped_column(Float, nullable=True)
    recommendations: Mapped[dict | None] = mapped_column(JSON, nullable=True)
    strategy_actions: Mapped[dict | None] = mapped_column(JSON, nullable=True)
    thinking_process: Mapped[str] = mapped_column(Text, default="")
    summary: Mapped[str] = mapped_column(Text, default="")
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.now)

    __table_args__ = (
        Index("ix_ai_report_date", "report_date"),
    )


class AIChatSession(Base):
    """Persistent chat session with Claude for follow-up questions."""

    __tablename__ = "ai_chat_sessions"

    id: Mapped[int] = mapped_column(primary_key=True)
    session_id: Mapped[str] = mapped_column(String(36), unique=True, index=True)
    claude_session_id: Mapped[str | None] = mapped_column(String(100), nullable=True)
    title: Mapped[str] = mapped_column(String(200), default="")
    messages: Mapped[list] = mapped_column(JSON, default=list)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.now)
    updated_at: Mapped[datetime] = mapped_column(
        DateTime, default=datetime.now, onupdate=datetime.now,
    )
